Fix irc link
commonlispbr/commonlispbr.github.io pull request #25
Opened 2018-02-17 20:39 UTC by ryukinix

Essa mudança faz com que o link do irc entre direto para
login no canal do #lisp-br

2018-02-18 03:31 UTC, ryukinix commented
Preciso corrigir os conflitos. Vou fazer amanhã

2018-02-26 00:06 UTC, luksamuk commented
Hmmm, talvez seja necessário alterar mais coisas para ajustar às novas alterações... devia ter visto esse PR antes.

2018-02-26 00:06 UTC, ryukinix commented
Vou fazer rebase dele aq

2018-02-26 00:10 UTC, ryukinix commented
@luksamuk resolvido magicamente os conflitos

2018-02-26 00:13 UTC, luksamuk requested changes

2018-02-26 00:13 UTC, luksamuk commented on index.org
> +Grupo não-oficial de Lisp Brasileiro IRC freenode: [[https://kiwiirc.com/client/chat.freenode.net:%2B6697/#lisp-br][#lisp-br]]
Poderia trocar o texto aqui para "Canal do IRC não-oficial de Lisp Brasileiro no Freenode:", como estava, para evitar esse texto mais convoluto? Acredito que o rebase criou essa regressão.

2018-02-26 00:52 UTC, ryukinix commented on index.org
> +Grupo não-oficial de Lisp Brasileiro IRC freenode: [[https://kiwiirc.com/client/chat.freenode.net:%2B6697/#lisp-br][#lisp-br]]
Tá bom

2018-02-26 00:53 UTC, ryukinix commented on index.org
> +Grupo não-oficial de Lisp Brasileiro IRC freenode: [[https://kiwiirc.com/client/chat.freenode.net:%2B6697/#lisp-br][#lisp-br]]
DONE

2018-02-26 02:36 UTC, luksamuk approved these changes
Aeeeee! Agora vai!

2018-02-26 02:36 UTC, merged